### ISSUE TITLE
add enemy #2 which traverses the maze similarly as the player does

### ISSUE THREAD

**Issue by wahiqq** [muskananeja/project350#17]

**Comment by wahiqq** [comment]
After executing, the CLI tower changes place

**Comment by muskananeja** [comment]
the glitch enemy has an issue with the right border of the maze

**Comment by muskananeja** [comment]
the enemy image has to be added, player also

**Comment by muskananeja** [comment]
smoothen out movements of glitch enemy

**Comment by muskananeja** [comment]
Solved in a new branch - Enemy 2 , have to figure out merge - optional @ wahiq change the bug image
