### ISSUE TITLE
Add command to pause enemy for certain time but with penalty

### ISSUE THREAD

**Issue by wahiqq** [muskananeja/project350#19]

**Comment by wahiqq** [comment]
Add penalty: Slow down the player and increase enemy speed

**Comment by adityaswamii** [comment]
Command to pause/freeze enemy implemented, enemy is unable to catch player when frozen (even if player walks by enemy). Upon unfreezing, the enemy's speed is increased many-fold and the player takes a severe hit in speed as penalty.

Will need reworking upon introduction of enemy 2
