### ISSUE TITLE
Unable to pass the CLI

### ISSUE THREAD

**Issue by wahiqq** [muskananeja/project350#7]
Unable to pass the CLI of CLI is in way of the solution.

**Comment by adityaswamii** [comment]
Using the exit command now gives the user plenty of time to walk through the cli a few times before its cooldown ends

**Comment by wahiqq** [comment]
The Command Line cooldown only works for the "exit command"

**Comment by wahiqq** [comment]
Using any now gives the user plenty of time to walk through the cli a few times before its cooldown ends
